import type { Metadata } from 'next';
import { Libre_Baskerville, Poppins } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/layout/header';
import Footer from '@/components/layout/footer';

const poppins = Poppins({
  weight: ['400', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
});
const libre = Libre_Baskerville({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
});

export const metadata: Metadata = {
  title: 'Haruma',
  description: 'Generated by create next app',
};

export const experimental_ppr = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${libre.variable} antialiased`}>
        <div className="bg-gradient-to-r from-red-100 via-red-50 to-red-100 font-sans text-foreground flex flex-col items-center justify-center px-16 py-12 gap-8">
          <Header />
          <main className="min-h-[calc(100svh-403px)] w-full flex flex-col items-center gap-16 py-4">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
